# Generated by Django 2.2.24 on 2021-07-01 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='puboished_date',
            new_name='published_date',
        ),
    ]
